on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/nuget.yaml"
      - "Fluenv/.."

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: astorDev/versy/calver/nuget@main
        with:
          project: Fluenv/Fluenv
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}